export { default as HeroBG } from './HeroBG.png';
export { default as LoginScreen } from './LoginScreen.png';
export { default as AccountCreation } from './AccountCreation.png';
export { default as Home } from './Home.png';
export { default as OverTheCounter } from './Over the counter.png';
export { default as SelectPartnerBank } from './Select Partner Banks.png';
export { default as Remittance } from './Partners and Remittance.png';
export { default as ReviewAndTransfer } from './Review and Transfer.png';
export { default as ConfirmationScreen } from './Confirmation Screen.png';
export { default as ConfirmationComplete } from './Confirmation Screen-1.png';
export { default as Send } from './Send.png';
export { default as SyncContacts } from './Sync Contacts.png';
export { default as OneTimePassword } from './Send to_Op1.png';
export { default as SendMoney } from './Send Money.png';
export { default as ConfirmSendMoney } from './Send Money Confirmation.png';
export { default as CompleteSendMoney } from './Send Money Complete.png';
export { default as EdLogo } from './ed.png';
